### ISSUE TITLE
Add Documentation

### ISSUE THREAD

**Issue by kadamwhite** [humanmade/webpack-helpers#10]
We've had some good discussions recently about how this project would _greatly_ benefit from better documentation around how to set this up and get started. Pinging @goldenapples and @smccafferty to help fill out a checklist of things you'd like to see!

**Comment by smccafferty** [comment]
The work recently done on Finder has been great reference material. While setting up another project recently I was using the webpack configurations as a basis however it only supports a single entry and output point currently [Ex. https://github.com/humanmade/finder_discovery/blob/master/.config/webpack.config.dev.js](https://github.com/humanmade/finder_discovery/blob/master/.config/webpack.config.dev.js). It would be beneficial to have an example configuration that would allow multiple entry/outputs.

**Comment by kadamwhite** [comment]
Closed in #12
