### ISSUE TITLE
CleanPlugin is not a constructor

### ISSUE THREAD

**Issue by kucrut** [humanmade/webpack-helpers#105]
The exported class from `clean-webpack-plugin` package is actually called [`CleanWebpackPlugin`](https://github.com/johnagan/clean-webpack-plugin/blob/021d2b68efd18fbd99e02c169d9e32300f15b4f4/src/clean-webpack-plugin.ts#L356), not [`CleanPlugin`](https://github.com/humanmade/webpack-helpers/blob/dc005019fcacd5f9d428cedbae35a47be9a6354a/src/plugins.js#L2).

**Comment by kadamwhite** [comment]
I believe this should be resolved as of #106
