### ISSUE TITLE
Instance properties not supported out of the box

### ISSUE THREAD

**Issue by tfrommen** [humanmade/webpack-helpers#24]
I was wondering why instance properties are not supported by the Babel preset/config.

I am used to write stateful class-based components like so:

```js
class Foo {
    state = {
        foo: 'bar',
    };
}
```

And I'm sure I'm not alone ... am I? 😁

 @kadamwhite - can we add the `@babel/plugin-proposal-class-properties` Babel plugin, please? Or do you expect it to not be used regularly?

**Comment by goldenapples** [comment]
If we're talking about customizing Babel config, the one that I always get bit by not having is [`@babel/plugin-proposal-object-rest-spread`](https://babeljs.io/docs/en/babel-plugin-proposal-object-rest-spread).

I'm not 100% sure it belongs here, but I would love to see this repo provide a common set of babel presets to be able to use a few agreed upon es-next features across projects. :+1: from me.

**Comment by tfrommen** [comment]
@goldenapples I agree, in general. But specifically for object rest spread, this is not a problem, because this is included in [the WordPress Babel preset](https://github.com/WordPress/gutenberg/blob/bb50415ab03839577866a0534fdc45caa52f43f5/packages/babel-preset-default/index.js#L57), which is [used by this package](https://github.com/humanmade/webpack-helpers/blob/master/babel-preset.js#L2). 🙂

**Comment by kadamwhite** [comment]
I’d be in favor of supporting static properties! Hadn’t bit me yet because I write very little class-based JS :grimacing:

**Comment by kadamwhite** [comment]
And @goldenapples as of last week this repo now does provide such a preset; see the Babel section of the getting started guide! Any suggestions for improvements are welcome.
