### ISSUE TITLE
webpack config expects an index key in the entry object

### ISSUE THREAD

**Issue by pdewouters** [humanmade/webpack-helpers#30]
It seems the prod config will only build if there is an `index` key in the `entry` object:

```
module.exports = presets.production( {
	name: 'theme',
	entry: {
                 // This works
		index: 'content/themes/best-theme-ever/src/theme.js',
                // This throws an error
		foo: 'content/themes/best-theme-ever/src/foo.js',
	},
      ....
} );
```

Error: 
```
ERROR in Entry module not found: Error: Can't resolve '/path/to/project/src/index.js' in '/path/to/project/content'
```

I think this is because in the default config, there is a default set to `index`.

cc @mattheu

**Comment by mattheu** [comment]
Thanks for raising this one. Yes I also ran into this issue. I wanted to name my file `theme` but found I wasn't able to do so.
