### ISSUE TITLE
Update clean-webpack-plugin and include as default for production builds. 

### ISSUE THREAD

**Issue by mattheu** [humanmade/webpack-helpers#31]
It would be nice to include [`clean-webpack-plugin`](https://www.npmjs.com/package/clean-webpack-plugin) for production builds to ensure the build directory doesn't contain any old files.

Let me know your thoughts - happy to open a PR for this.

**Comment by mattheu** [comment]
Such an idiot - didn't see this was bundled. 

However - the version bundled is `1.0`, but the plugin is now at `3.0`. The latest version doesn't require you to pass `paths`, if you just call `new CleanPlugin()` then it automatically cleans the webpack output path - zero config required.  So currently its less config to just use the plugin directly and skip the `webpack-helpers` version.

Additionally... any reason not to just clean the webpack output path by default for production builds?

**Comment by kadamwhite** [comment]
No strong opinions on cleaning by default, I think if I consider your argument for long enough you'll have me convinced. We should definitely update the dependency, nice catch.

**Comment by kadamwhite** [comment]
We cannot actually clean by default, because then if somebody does
```js
module.exports = [
  presets.production( { ... } ),
  presets.production( { ... } ),
];
```
then only one build will get output correctly (whichever runs second will clear the build folder, removing all files from the first-run build). However, this can be added as an option, for sure.
