### ISSUE TITLE
Idea: Add a system bell

### ISSUE THREAD

**Issue by igmoweb** [humanmade/webpack-helpers#41]
A silly idea that will probably go nowhere: Sometimes I'm developing without the console opened and if I made a mistake the bundle is not generated again but I spend some time figuring out why my changes aren't appearing.

There's a simple webpack plugin for that: https://www.npmjs.com/package/bell-on-bundler-error-plugin

I include it in all my personal projects so I thought it could be handy here.

**Comment by johnbillion** [comment]
Yes please. Other build tools I've used ring a bell when there's an error and it's really useful.

**Comment by igmoweb** [comment]
Gonna ping @kadamwhite here to give his view.

**Comment by johnbillion** [comment]
Happy to do a PR for this as I just implemented it on a project.
